# Generated by Django 4.2.15 on 2024-08-26 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='position',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2),
        ),
    ]
