# Generated by Django 4.2.15 on 2024-08-27 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MapQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('edges', models.JSONField()),
                ('type', models.IntegerField()),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
                ('map_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.mapcheck')),
            ],
        ),
    ]
