# Generated by Django 4.2.15 on 2024-09-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_mapcheck_mapquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50)),
            ],
        ),
    ]
